services:
  web:
    image: mattfly/global-signbank:latest
    ports:
      - '8000:8000'
    volumes:
      # Writable data persistence
      - signbank_data:/app/writable
    environment:
      - DEBUG=False
      - SECRET_KEY=change-this-secret-key-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
    stdin_open: true
    tty: true

volumes:
  signbank_data:

